FROM docker.liangzixin.top/library/nginx:v1.1.1
COPY dist /usr/share/nginx/html
COPY docker/nginx.80.conf /etc/nginx/conf.d/nginx.80.conf
RUN rm -f /etc/nginx/nginx.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf

LABEL maintainer="liangzixin.top"

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
