
server:
  maxHttpHeaderSize: 102400
  port: 9301
management:
  endpoints:
    web.exposure.include: "*"
  server:
    port: 9601

spring:
  application:
    name: svc-platform-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.89.91.168:8806/lzx_ci_sample?characterEncoding=utf8&useSSL=false
    username: lzx_owner
    password: 1qaz2WSX

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: top.liangzixin.cisample.svc.platform.entity.entity
  global-config:
    id-type: 0
    db-column-underline: true

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 50 #核心线程池
      maximumSize: 10000 #支持的最大并发量
      allowMaximumSizeToDivergeFromCoreSize: true #允许 maximumSize 生效
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 22000

ribbon:
  ConnectTimeOut: 3000
  ReadTimeout: 4000
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  ServerListRefreshInterval: 5000

log:
  path: svc-user-logs

logging:
  level.top.liangzixin.cisample.svc.platform.user: debug